In [14]:
import requests
import re
import json
import pandas as pd
import datetime
from pandas.io.json import json_normalize
from bs4 import BeautifulSoup
from collections import defaultdict



def get_dartOpenApi(code='005930', docs='사업,반기,분기', start_date='20010101', end_date=''):
    
    # 전자공시 오픈API 참조 : http://dart.fss.or.kr/dsap001/guide.do
    
    auth = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'             # 전자공시 오픈API 인증키
    headers={'Referer':'https://dart.fss.or.kr/dsap001/guide.do'} # 헤더: 실제 인증키를 사용시 사용하지 않아도 된다

    bsn_tps = ''
    dart_docs = []
    
    """ 아래 코드가 python스럽지만, 실행속도 측면에서는 그닥 ...
    if re.search('사업', docs): dart_docs.append('사업보고서')
    if re.search('반기', docs): dart_docs.append('반기보고서')   
    if re.search('분기', docs): dart_docs.append('분기보고서')   
    dart_bsn_tps = {'사업보고서' : 'A001', '반기보고서' : 'A002', '분기보고서' : 'A003'}
    for doc in dart_docs:
        bsn_tps += '&bsn_tp=' + dart_bsn_tps[doc]
    """
    if re.search('사업', docs): dart_docs.append('A001') 
    if re.search('반기', docs): dart_docs.append('A002')
    if re.search('분기', docs): dart_docs.append('A003') 
    if re.search('수시', docs): dart_docs.append('I001')     
    for i in range(0, len(dart_docs)):
        bsn_tps += '&bsn_tp=' + dart_docs[i]

    url_format = ('http://dart.fss.or.kr/api/search.json?auth={auth}&crp_cd={code}' 
                    '&start_dt={start_date}&end_dt={end_date}&%s&page_set=100')
    url = url_format.format(auth=auth, code=code, start_date=start_date, end_date=end_date) % bsn_tps
    r = requests.get(url, headers=headers)
    jo = json.loads(r.text)
    result = json_normalize(jo, 'list')
    
    return result



def get_dartDocUrls(code='005930', docs='사업,반기,분기', start_date='20010101', end_date=''):
    
    df_api = get_dartOpenApi(code, docs, start_date, end_date)
    urls = []
    for i, rcpNo in df_api.iterrows():
        url_format = 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo={}'
        url = url_format.format(rcpNo['rcp_no'])
        urls.append(url)
    
    return urls
   
    
    
def get_dartDocTocUrls(head_url, toc_doc=''):
    
    # 공시보고서 목차(toc:table of contents) url들 리턴
    # toc_doc=목차제목 => 선택한 목차 url 리턴
    
    rcpNo = head_url[-14:]   # head_url = "http://dart.fss.or.kr/dsaf001/main.do?rcpNo={rcpNo:14자리}
    r = requests.get(head_url)

    reg = re.compile('viewDoc\((.*)\);')
    params = []
    matches = reg.findall(r.text)
    for m in matches: 
        params.append(m.replace("'", "").replace(" ", "").split(","))
   
    url_format = ('http://dart.fss.or.kr/report/viewer.do?rcpNo=%s'
                        '&dcmNo=%s&eleId=%s&offset=%s&length=%s&dtd=%s')
    urls = []
    for p in params:
        if rcpNo == p[0]: urls.append(url_format % tuple(p))
            
    if toc_doc != '':
        if   re.search('회사', toc_doc): toc_num = 3
        elif re.search('사업', toc_doc): toc_num = 10
        elif re.search('재무', toc_doc): toc_num = 11
        elif re.search('감사인', toc_doc): toc_num = 18
        elif re.search('이사', toc_doc): toc_num = 19
        elif re.search('이사회', toc_doc): toc_num = 20
        elif re.search('주주', toc_doc): toc_num = 24
        elif re.search('임원', toc_doc): toc_num = 25
        elif re.search('계열회사', toc_doc): toc_num = 28
        elif re.search('이해관계자', toc_doc): toc_num = 29
        elif re.search('그 밖에', toc_doc): toc_num = 30
        elif re.search('전문가', toc_doc): toc_num = 31
        urls = urls[toc_num-1]
        
    return urls



def get_dartDocHtmlTable(doc_url, table_num=0):
    
    r = requests.get(doc_url)
    bs = BeautifulSoup(r.text, 'lxml')
    tables = bs.find_all('table')
    table = tables[table_num-1]
    df = get_htmlTable(table)
    
    return df



def get_htmlTable(table):
    
    """ ******************************************************************************************************
     get_htmlTable() : rowspan, colspan된 html table을 pandas dataframe으로 리턴
       - HTML table에 헤더가 없으면 아래 b.만 실행
       - 참조 코드 : https://stackoverflow.com/questions/9978445/parsing-a-table-with-rowspan-and-colspan   
    ==========================================================================================================
     입력인수 table은 html table, <table> ... </table>
     ----------------------------------------------------------------------------------------------------------
     a. 테이블 헤더에서, <theader>...<tr>...<th rowspan="rx" colspan="cy"> th_data </th>...</tr>...</theader>
        a1. rowspan된 개수(rx-1)만큼 아래쪽 행에 th_data 삽입
        a2. colspan된 개수(cy-1)만큼 오른쪽 열에 th_data 삽입
        a3. 테이블 헤더가 존재할 때, 헤더(th)에 rowspan, colspan이 있으면 헤더를 한개 행으로 병합, 상위 항목값은 [ ]로 병합
             -----------------------
            | X |     Y     |   Z   |       --------------------------------------
            |   |-------------------   =>  | X | A[Y] | B[Y] | C[Y] | D[Z] | E[Z] |
            |   | A | B | C | D | E |       --------------------------------------
             -----------------------
    ----------------------------------------------------------------------------------------------------------
     b. 테이블 바디에서, <tbody>...<tr>...<td rowspan="rx" colspan="cy"> td_data </td>...</tr>...</tbody>
        - rowspan된 개수(rx-1)만큼 아래쪽 행에 td_data 삽입
        - colspan된 개수(cy-1)만큼 오른쪽 열에 'NaN' 삽입
    ==========================================================================================================
     기타. 딕셔너리를 리스트로 하면 코딩이 편할 듯 한데, tbody_dct = defaultdict(list), 리스트 딕셔너리 ?
    ****************************************************************************************************** """
    
    thead = defaultdict(lambda : defaultdict(str)) 
    tbody = defaultdict(lambda : defaultdict(str))      
    for trow, tr in enumerate(table.find_all('tr')):
        # run a1. and a2.
        for tcol, th in enumerate(tr.find_all('th')):
            colspan = int(th.get('colspan', 1))             # colspan이 없으면, colspan = 1
            rowspan = int(th.get('rowspan', 1))             # rowspan이 없으면, rowspan = 1
            th_data = th.get_text(strip=True)               # 줄 바꿈('\n') 떼버림(strip)
            while trow in thead and tcol in thead[trow]:
                tcol += 1
            for i in range(trow, trow + rowspan):
                for j in range(tcol, tcol + colspan):       
                    thead[i][j] = th_data                   # rowspan, colspan된 th에 th_data 삽입
        # run b.
        for tcol, td in enumerate(tr.find_all('td')):
            colspan = int(td.get('colspan', 1))             # colspan이 없으면, colspan = 1
            rowspan = int(td.get('rowspan', 1))             # rowspan이 없으면, rowspan = 1
            td_data = td.get_text(strip=True)               # 줄 바꿈('\n') 떼버림(strip)
            while trow in tbody and tcol in tbody[trow]:
                tcol += 1
            for i in range(trow, trow + rowspan):
                tbody[i][tcol] = td_data                    # rowspan된 td에 td_data 삽입
                for j in range(tcol + 1, tcol + colspan):
                    tbody[i][j] = 'NaN'                     # colspan된 td에 NaN 삽입
    
    tbody = list(dict_to_listArray(tbody))                  # tbody(딕셔너리)를 tbdody(리스트 어레이)로 변환 

    # run a3.
    if table.find('thead') != None:  
        th_row = len(thead)-1
        for i in range(th_row-1, -1, -1):
            for j in range(0, len(thead[th_row])):
                if thead[th_row][j] != thead[i][j]:
                    thead[th_row][j] += '[' + thead[i][j] + ']'
        thead = thead[th_row].values()                      # thead(딕셔너리)의 마지막 element를 리스트로 변환
        df = pd.DataFrame(data = tbody, columns = thead)
    else:
        thead_list = []
        df = pd.DataFrame(data = tbody)
    
    return df

        
    
def dict_to_listArray(dict):
    
    for i, row in sorted(dict.items()):
        cols = []
        for j, col in sorted(row.items()):
            cols.append(col)
        yield cols      

        
        
def get_dartSpecificDocUrl(code='005930', doc='사업보고서', doc_date='2016.12'):
      
    date = doc_date.split('.')
    year = date[0]
    month = date[1]
    day = '30'

    # 보고서 3개월 이내 공시, 100일 후로 검색종료 일자 변경
    if month == '1Q' or month == '1q': month = '03'
    if month == '2Q' or month == '2q': month = '06'
    if month == '3Q' or month == '3q': month = '09'
    if month == '4Q' or month == '4q': month = '12'

    date = datetime.date(int(year), int(month), int(day))
    end_date = date + datetime.timedelta(days=100)
    end_date = str(end_date).replace('-','')
    start_date = year + month + day

    df_api = get_dartOpenApi(code, doc, start_date, end_date)

    if   re.search('사업', doc): doc_find = '사업보고서' + '\(' + year + '.' + month + '\)'
    elif re.search('반기', doc): doc_find = '반기보고서' + '\(' + year + '.' + month + '\)'
    elif re.search('분기', doc): doc_find = '분기보고서' + '\(' + year + '.' + month + '\)'

    for ix, rpt_nm in df_api.iterrows():
        if re.search(doc_find, rpt_nm['rpt_nm'].replace(' ','')):
            url_format = 'http://dart.fss.or.kr/dsaf001/main.do?rcpNo={}'
            url = url_format.format(rpt_nm['rcp_no'])
            break
    
    return url



def get_dartSpecificDocHtmlTable(code='005930', doc='사업보고서', doc_date='2016.12', toc_doc='사업', table_num=1):

    doc_url = get_dartSpecificDocUrl(code, doc, doc_date)
    toc_url = get_dartDocTocUrls(doc_url, toc_doc)

    return get_dartDocHtmlTable(toc_url, table_num)

In [15]:
result = get_dartOpenApi(code='005930', docs='사업보고서', start_date='20100101', end_date='20170101')
result

,crp_cd,crp_cls,crp_nm,flr_nm,rcp_dt,rcp_no,rmk,rpt_nm
0,005930,Y,삼성전자,삼성전자,20160330,20160330003536,연,사업보고서 (2015.12)
1,005930,Y,삼성전자,삼성전자,20150331,20150331002915,연,사업보고서 (2014.12)
2,005930,Y,삼성전자,삼성전자,20140331,20140331002427,연,사업보고서 (2013.12)
3,005930,Y,삼성전자,삼성전자,20130401,20130401003031,연,사업보고서 (2012.12)
4,005930,Y,삼성전자,삼성전자,20120330,20120330002110,연,[첨부추가]사업보고서 (2011.12)
5,005930,Y,삼성전자,삼성전자,20110331,20110331002193,연,[첨부추가]사업보고서 (2010.12)
6,005930,Y,삼성전자,삼성전자,20100331,20100331001680,연,[첨부추가]사업보고서 (2009.12)

In [16]:
result = get_dartDocUrls(code='005930', docs='사업보고서', start_date='20100101', end_date='20170101')
result[0]

'http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20160330003536'

In [17]:
doc_urls = get_dartDocTocUrls(result[0])
doc_urls

['http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=1&offset=712&length=4053&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=2&offset=12770&length=410&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=3&offset=13184&length=232563&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=4&offset=13283&length=138879&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=5&offset=152166&length=20381&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=6&offset=172551&length=3614&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=7&offset=176169&length=54264&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=8&offset=230437&length=6828&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=9&offset=237269&length=8464&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=10&offset=245751&length=217728&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=11&offset=463483&length=1307314&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=12&offset=463601&length=20836&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=13&offset=484673&length=108645&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=14&offset=593322&length=497570&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=15&offset=1090896&length=90302&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=16&offset=1181202&length=421680&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=17&offset=1602912&length=167871&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=18&offset=1770801&length=14903&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=19&offset=1785708&length=41882&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=20&offset=1827594&length=51998&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=21&offset=1827707&length=41239&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=22&offset=1868950&length=9975&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=23&offset=1878929&length=649&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=24&offset=1879596&length=58881&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=25&offset=1938481&length=632284&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=26&offset=1938593&length=607535&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=27&offset=2546132&length=24619&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=28&offset=2570769&length=443004&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=29&offset=3013777&length=47335&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=30&offset=3061116&length=13893&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=31&offset=3075013&length=337&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=32&offset=3075105&length=112&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=33&offset=3075221&length=115&dtd=dart3.xsd',
 'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=1&offset=712&length=4053&dtd=dart3.xsd']

In [18]:
doc_urls = get_dartDocTocUrls(result[0], toc_doc='사업')
doc_urls

'http://dart.fss.or.kr/report/viewer.do?rcpNo=20160330003536&dcmNo=5026126&eleId=10&offset=245751&length=217728&dtd=dart3.xsd'

In [19]:
df = get_dartDocHtmlTable(doc_urls, table_num=11)

print(df)
df

      부문   부문   구  분     금액[제47기] 비중[제47기]     금액[제46기] 비중[제46기]     금액[제45기]  \
0   CE부문  NaN   총매출액  120,688,835    24.5%  124,916,892    25.3%  125,088,762
1   CE부문  NaN  내부매출액   73,793,424    25.2%   74,733,757    25.9%   74,757,247
2   CE부문  NaN   순매출액   46,895,411    23.4%   50,183,135    24.3%   50,331,515
3   CE부문  NaN   영업이익    1,254,187     4.7%    1,184,325     4.7%    1,673,343
4   CE부문  NaN    총자산   45,998,007    12.8%   43,116,374    12.8%   47,183,953
5   IM부문  NaN   총매출액  222,023,600    45.0%  236,438,979    47.9%  299,161,654
6   IM부문  NaN  내부매출액  118,469,345    40.5%  124,674,435    43.3%  160,344,435
7   IM부문  NaN   순매출액  103,554,255    51.6%  111,764,544    54.2%  138,817,219
8   IM부문  NaN   영업이익   10,142,022    38.4%   14,562,885    58.2%   24,957,741
9   IM부문  NaN    총자산   98,463,323    27.4%   94,227,108    27.9%   86,132,881
10  DS부문  반도체   총매출액   90,600,806    18.4%   75,058,071    15.2%   70,908,145
11  DS부문  반도체  내부매출액   43,014,054    14.7%   35,328,169    12.3%   33,471,566
12  DS부문  반도체   순매출액   47,586,752    23.7%   39,729,902    19.3%   37,436,579
13  DS부문  반도체   영업이익   12,787,297    48.4%    8,776,442    35.1%    6,887,978
14  DS부문  반도체    총자산   98,989,253    27.6%   87,567,196    25.9%   76,224,096
15  DS부문   DP   총매출액   55,120,243    11.2%   52,227,615    10.6%   61,294,886
16  DS부문   DP  내부매출액   27,633,382     9.4%   26,500,446     9.2%   31,457,770
17  DS부문   DP   순매출액   27,486,861    13.7%   25,727,169    12.5%   29,837,116
18  DS부문   DP   영업이익    2,295,367     8.7%      660,181     2.6%    2,980,563
19  DS부문   DP    총자산   50,147,263    14.0%   46,826,533    13.8%   42,195,558
20  DS부문    계   총매출액  149,974,731    30.4%  131,459,756    26.6%  134,394,781
21  DS부문    계  내부매출액   74,948,617    25.6%   65,669,950    22.8%   66,633,875
22  DS부문    계   순매출액   75,026,114    37.4%   65,789,806    31.9%   67,760,906
23  DS부문    계   영업이익   14,887,262    56.4%    9,430,915    37.7%   10,000,665
24  DS부문    계    총자산  174,264,841    48.5%  160,138,321    47.4%  145,872,686

   비중[제45기]
0     22.4%
1     22.7%
2     22.0%
3      4.5%
4     14.9%
5     53.6%
6     48.7%
7     60.7%
8     67.8%
9     27.1%
10    12.7%
11    10.2%
12    16.4%
13    18.7%
14    24.0%
15    11.0%
16     9.5%
17    13.0%
18     8.1%
19    13.3%
20    24.1%
21    20.2%
22    29.6%
23    27.2%
24    45.9%

,부문,부문,구 분,금액[제47기],비중[제47기],금액[제46기],비중[제46기],금액[제45기],비중[제45기]
0,CE부문,NaN,총매출액,"120,688,835",24.5%,"124,916,892",25.3%,"125,088,762",22.4%
1,CE부문,NaN,내부매출액,"73,793,424",25.2%,"74,733,757",25.9%,"74,757,247",22.7%
2,CE부문,NaN,순매출액,"46,895,411",23.4%,"50,183,135",24.3%,"50,331,515",22.0%
3,CE부문,NaN,영업이익,"1,254,187",4.7%,"1,184,325",4.7%,"1,673,343",4.5%
4,CE부문,NaN,총자산,"45,998,007",12.8%,"43,116,374",12.8%,"47,183,953",14.9%
5,IM부문,NaN,총매출액,"222,023,600",45.0%,"236,438,979",47.9%,"299,161,654",53.6%
6,IM부문,NaN,내부매출액,"118,469,345",40.5%,"124,674,435",43.3%,"160,344,435",48.7%
7,IM부문,NaN,순매출액,"103,554,255",51.6%,"111,764,544",54.2%,"138,817,219",60.7%
8,IM부문,NaN,영업이익,"10,142,022",38.4%,"14,562,885",58.2%,"24,957,741",67.8%
9,IM부문,NaN,총자산,"98,463,323",27.4%,"94,227,108",27.9%,"86,132,881",27.1%
10,DS부문,반도체,총매출액,"90,600,806",18.4%,"75,058,071",15.2%,"70,908,145",12.7%
11,DS부문,반도체,내부매출액,"43,014,054",14.7%,"35,328,169",12.3%,"33,471,566",10.2%
12,DS부문,반도체,순매출액,"47,586,752",23.7%,"39,729,902",19.3%,"37,436,579",16.4%
13,DS부문,반도체,영업이익,"12,787,297",48.4%,"8,776,442",35.1%,"6,887,978",18.7%
14,DS부문,반도체,총자산,"98,989,253",27.6%,"87,567,196",25.9%,"76,224,096",24.0%
15,DS부문,DP,총매출액,"55,120,243",11.2%,"52,227,615",10.6%,"61,294,886",11.0%
16,DS부문,DP,내부매출액,"27,633,382",9.4%,"26,500,446",9.2%,"31,457,770",9.5%
17,DS부문,DP,순매출액,"27,486,861",13.7%,"25,727,169",12.5%,"29,837,116",13.0%
18,DS부문,DP,영업이익,"2,295,367",8.7%,"660,181",2.6%,"2,980,563",8.1%
19,DS부문,DP,총자산,"50,147,263",14.0%,"46,826,533",13.8%,"42,195,558",13.3%
20,DS부문,계,총매출액,"149,974,731",30.4%,"131,459,756",26.6%,"134,394,781",24.1%
21,DS부문,계,내부매출액,"74,948,617",25.6%,"65,669,950",22.8%,"66,633,875",20.2%
22,DS부문,계,순매출액,"75,026,114",37.4%,"65,789,806",31.9%,"67,760,906",29.6%
23,DS부문,계,영업이익,"14,887,262",56.4%,"9,430,915",37.7%,"10,000,665",27.2%
24,DS부문,계,총자산,"174,264,841",48.5%,"160,138,321",47.4%,"145,872,686",45.9%

In [20]:
# 위 일련 실행이, 아래 코드와 동일함
df = get_dartSpecificDocHtmlTable(code='005930', doc='사업보고서', doc_date='2016.12', toc_doc='사업', table_num=11)

print(df)
df

      부문   부문   구  분     금액[제48기] 비중[제48기]     금액[제47기] 비중[제47기]     금액[제46기]  \
0   CE부문  NaN   총매출액  109,672,506    22.8%  120,688,835    24.5%  124,916,892
1   CE부문  NaN  내부매출액   62,627,083    22.4%   73,793,424    25.2%   74,733,757
2   CE부문  NaN   순매출액   47,045,423    23.3%   46,895,411    23.4%   50,183,135
3   CE부문  NaN   영업이익    2,638,002     9.0%    1,254,187     4.7%    1,184,325
4   CE부문  NaN    총자산   49,675,022    13.6%   45,998,007    12.8%   43,116,374
5   IM부문  NaN   총매출액  211,523,973    43.9%  222,023,600    45.0%  236,438,979
6   IM부문  NaN  내부매출액  111,221,861    39.7%  118,469,345    40.5%  124,674,435
7   IM부문  NaN   순매출액  100,302,112    49.7%  103,554,255    51.6%  111,764,544
8   IM부문  NaN   영업이익   10,807,569    37.0%   10,142,022    38.4%   14,562,885
9   IM부문  NaN    총자산  111,574,049    30.5%   98,463,323    27.4%   94,227,108
10  DS부문  반도체   총매출액   99,527,926    20.6%   90,600,806    18.4%   75,058,071
11  DS부문  반도체  내부매출액   48,370,924    17.3%   43,014,054    14.7%   35,328,169
12  DS부문  반도체   순매출액   51,157,002    25.3%   47,586,752    23.7%   39,729,902
13  DS부문  반도체   영업이익   13,595,004    46.5%   12,787,297    48.4%    8,776,442
14  DS부문  반도체    총자산  102,251,069    28.0%   98,989,253    27.6%   87,567,196
15  DS부문   DP   총매출액   55,884,739    11.6%   55,120,243    11.2%   52,227,615
16  DS부문   DP  내부매출액   28,956,095    10.3%   27,633,382     9.4%   26,500,446
17  DS부문   DP   순매출액   26,928,644    13.3%   27,486,861    13.7%   25,727,169
18  DS부문   DP   영업이익    2,226,626     7.6%    2,295,367     8.7%      660,181
19  DS부문   DP    총자산   57,240,065    15.6%   50,147,263    14.0%   46,826,533
20  DS부문    계   총매출액  159,473,455    33.1%  149,974,731    30.4%  131,459,756
21  DS부문    계  내부매출액   81,325,252    29.0%   74,948,617    25.6%   65,669,950
22  DS부문    계   순매출액   78,148,203    38.7%   75,026,114    37.4%   65,789,806
23  DS부문    계   영업이익   15,850,986    54.2%   14,887,262    56.4%    9,430,915
24  DS부문    계    총자산  183,951,625    50.3%  174,264,841    48.5%  160,138,321

   비중[제46기]
0     25.3%
1     25.9%
2     24.3%
3      4.7%
4     12.8%
5     47.9%
6     43.3%
7     54.2%
8     58.2%
9     27.9%
10    15.2%
11    12.3%
12    19.3%
13    35.1%
14    25.9%
15    10.6%
16     9.2%
17    12.5%
18     2.6%
19    13.8%
20    26.6%
21    22.8%
22    31.9%
23    37.7%
24    47.4%

,부문,부문,구 분,금액[제48기],비중[제48기],금액[제47기],비중[제47기],금액[제46기],비중[제46기]
0,CE부문,NaN,총매출액,"109,672,506",22.8%,"120,688,835",24.5%,"124,916,892",25.3%
1,CE부문,NaN,내부매출액,"62,627,083",22.4%,"73,793,424",25.2%,"74,733,757",25.9%
2,CE부문,NaN,순매출액,"47,045,423",23.3%,"46,895,411",23.4%,"50,183,135",24.3%
3,CE부문,NaN,영업이익,"2,638,002",9.0%,"1,254,187",4.7%,"1,184,325",4.7%
4,CE부문,NaN,총자산,"49,675,022",13.6%,"45,998,007",12.8%,"43,116,374",12.8%
5,IM부문,NaN,총매출액,"211,523,973",43.9%,"222,023,600",45.0%,"236,438,979",47.9%
6,IM부문,NaN,내부매출액,"111,221,861",39.7%,"118,469,345",40.5%,"124,674,435",43.3%
7,IM부문,NaN,순매출액,"100,302,112",49.7%,"103,554,255",51.6%,"111,764,544",54.2%
8,IM부문,NaN,영업이익,"10,807,569",37.0%,"10,142,022",38.4%,"14,562,885",58.2%
9,IM부문,NaN,총자산,"111,574,049",30.5%,"98,463,323",27.4%,"94,227,108",27.9%
10,DS부문,반도체,총매출액,"99,527,926",20.6%,"90,600,806",18.4%,"75,058,071",15.2%
11,DS부문,반도체,내부매출액,"48,370,924",17.3%,"43,014,054",14.7%,"35,328,169",12.3%
12,DS부문,반도체,순매출액,"51,157,002",25.3%,"47,586,752",23.7%,"39,729,902",19.3%
13,DS부문,반도체,영업이익,"13,595,004",46.5%,"12,787,297",48.4%,"8,776,442",35.1%
14,DS부문,반도체,총자산,"102,251,069",28.0%,"98,989,253",27.6%,"87,567,196",25.9%
15,DS부문,DP,총매출액,"55,884,739",11.6%,"55,120,243",11.2%,"52,227,615",10.6%
16,DS부문,DP,내부매출액,"28,956,095",10.3%,"27,633,382",9.4%,"26,500,446",9.2%
17,DS부문,DP,순매출액,"26,928,644",13.3%,"27,486,861",13.7%,"25,727,169",12.5%
18,DS부문,DP,영업이익,"2,226,626",7.6%,"2,295,367",8.7%,"660,181",2.6%
19,DS부문,DP,총자산,"57,240,065",15.6%,"50,147,263",14.0%,"46,826,533",13.8%
20,DS부문,계,총매출액,"159,473,455",33.1%,"149,974,731",30.4%,"131,459,756",26.6%
21,DS부문,계,내부매출액,"81,325,252",29.0%,"74,948,617",25.6%,"65,669,950",22.8%
22,DS부문,계,순매출액,"78,148,203",38.7%,"75,026,114",37.4%,"65,789,806",31.9%
23,DS부문,계,영업이익,"15,850,986",54.2%,"14,887,262",56.4%,"9,430,915",37.7%
24,DS부문,계,총자산,"183,951,625",50.3%,"174,264,841",48.5%,"160,138,321",47.4%